import {useState} from 'react'
import {Navigate,useNavigate} from 'react-router-dom'
import {CheckCircle2,Sparkles} from 'lucide-react'
import {api,humanError,track} from '../api'
import {useAuth} from '../auth'
import Seo from '../components/Seo'
export default function CreatePage(){
  const{authenticated,loading}=useAuth();const navigate=useNavigate();const[text,setText]=useState('');const[analysis,setAnalysis]=useState(null);const[deadline,setDeadline]=useState('');const[probability,setProbability]=useState(50);const[criteria,setCriteria]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('')
  if(!loading&&!authenticated)return <Navigate to="/" replace/>
  const analyze=async()=>{setBusy(true);setError('');try{const{data}=await api.post('/forecasts/analyze',{text});const a=data.analysis;setAnalysis(a);setCriteria(a.resolution_criteria||'');if(a.deadline_at)setDeadline(new Date(a.deadline_at).toISOString().slice(0,16));if(a.suggested_author_probability!==null&&a.suggested_author_probability!==undefined)setProbability(Math.round(a.suggested_author_probability));track('forecast_analyze')}catch(e){setError(humanError(e,'Não foi possível analisar esta previsão.'))}finally{setBusy(false)}}
  const publish=async()=>{setBusy(true);setError('');try{const{data}=await api.post('/forecasts',{text,deadline_at:deadline?new Date(deadline).toISOString():null,author_probability:probability,category:analysis?.category,resolution_criteria:criteria});navigate('/previsao/'+data.forecast.slug)}catch(e){setError(humanError(e,'Não foi possível publicar esta previsão.'));if(e?.response?.data?.analysis)setAnalysis(e.response.data.analysis)}finally{setBusy(false)}}
  return <section className="composer-wrap"><Seo title="Criar previsão" description="Registre uma previsão verificável na Prevora." canonical="https://prevora.petertecnet.com.br/criar"/><div className="section-head"><div><span className="eyebrow">NOVA PREVISÃO</span><h1>O que você acredita que vai acontecer?</h1></div></div>{!analysis?<div className="composer"><textarea autoFocus value={text} onChange={e=>setText(e.target.value)} maxLength={1200} placeholder="Ex.: A empresa X anunciará um novo produto até dezembro de 2027."/><div className="composer-hint"><span>{text.trim().length}/1200</span><span>Escreva de forma natural. A Prevora estrutura prazo e critério de verificação.</span></div>{error&&<p className="notice error">{error}</p>}<button className="primary wide" disabled={text.trim().length<15||busy} onClick={analyze}>{busy?'Analisando…':'Analisar previsão'}</button></div>:<div className="analysis-panel"><div className="analysis-title"><Sparkles size={22}/><div><span>Análise estruturada</span><h2>{analysis.statement}</h2></div></div>{analysis.ambiguity?.length>0&&<div className="notice">{analysis.ambiguity.join(' ')}</div>}<div className="form-grid"><label>Categoria<input value={analysis.category||'Geral'} disabled/></label><label>Prazo<input type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label></div><label>Critério de resolução<textarea className="small-textarea" value={criteria} onChange={e=>setCriteria(e.target.value)}/></label><label className="prob-slider">Sua probabilidade <strong>{probability}%</strong><input type="range" min="0" max="100" value={probability} onChange={e=>setProbability(Number(e.target.value))}/></label><div className="analysis-check"><CheckCircle2 size={18}/><span>A publicação guarda seu texto original e o histórico de alterações.</span></div>{error&&<p className="notice error">{error}</p>}<div className="hero-actions"><button className="secondary" onClick={()=>setAnalysis(null)}>Editar texto</button><button className="primary" disabled={busy||!deadline||criteria.trim().length<12} onClick={publish}>{busy?'Publicando…':'Confirmar e publicar'}</button></div></div>}</section>
}