import {useEffect,useRef,useState} from 'react'
import {Sparkles,Zap} from 'lucide-react'
import {Link} from 'react-router-dom'
import {api} from '../api'
import ForecastCard from '../components/ForecastCard'
import Seo from '../components/Seo'
export default function HomePage(){
  const[items,setItems]=useState([]);const[meta,setMeta]=useState(null);const[page,setPage]=useState(1);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const sentinel=useRef(null)
  const load=async(next=1,append=false)=>{setLoading(true);try{const{data}=await api.get('/forecasts',{params:{page:next,per_page:20,sort:'trending'}});setItems(prev=>append?[...prev,...(data.data||[])]:data.data||[]);setMeta(data.meta);setPage(next);setError('')}catch{setError('Não foi possível carregar as previsões agora.')}finally{setLoading(false)}}
  useEffect(()=>{load(1)},[])
  useEffect(()=>{const node=sentinel.current;if(!node||!meta||page>=meta.last_page||loading)return;const observer=new IntersectionObserver(entries=>{if(entries[0]?.isIntersecting)load(page+1,true)},{rootMargin:'320px'});observer.observe(node);return()=>observer.disconnect()},[meta,page,loading])
  return <><Seo description="Registre previsões verificáveis, acompanhe probabilidades e construa reputação baseada em resultados reais." canonical="https://prevora.petertecnet.com.br/"/><section className="hero"><div><span className="eyebrow"><Sparkles size={15}/> inteligência coletiva sobre o futuro</span><h1>Onde previsões encontram a realidade.</h1><p>Registre o que você acredita que vai acontecer. A Prevora mede probabilidades, acompanha evidências e transforma histórico consistente em reputação.</p><div className="hero-actions"><Link className="primary" to="/criar"><Zap size={17}/>Fazer uma previsão</Link><Link className="secondary" to="/futuro">Explorar o futuro</Link></div></div><div className="signal-card"><span>Metodologia</span><strong>0–100%</strong><p>Probabilidade não é certeza. A plataforma separa estimativas do autor, comunidade e cálculo ponderado.</p></div></section><section className="section-head"><div><span className="eyebrow">AGORA</span><h2>Previsões da comunidade</h2></div></section>{error&&<div className="notice error">{error}<button onClick={()=>load(1)}>Tentar novamente</button></div>}{loading&&items.length===0&&<div className="skeleton-list">{[1,2,3].map(i=><div className="skeleton-card" key={i}/>)}</div>}{!loading&&items.length===0&&!error&&<div className="empty-card"><Sparkles size={34}/><h3>Ainda não há previsões publicadas.</h3><p>Seja o primeiro a registrar uma previsão verificável.</p><Link className="primary" to="/criar">Criar primeira previsão</Link></div>}<div className="feed">{items.map(item=><ForecastCard key={item.id} forecast={item}/>)}</div><div ref={sentinel} className="scroll-sentinel">{loading&&items.length>0?'Carregando mais…':''}</div></>
}