import {useEffect,useState} from 'react'
import {Bell,CircleUserRound,Home,Plus,Radar,Search,Trophy,LogOut,Grid2X2,Download} from 'lucide-react'
import {Link,NavLink} from 'react-router-dom'
import {useAuth,GoogleSignIn} from '../auth'
import {humanError} from '../api'
const nav=[['/',Home,'Início'],['/futuro',Radar,'Futuro'],['/ranking',Trophy,'Ranking'],['/perfil',CircleUserRound,'Perfil']]
export default function Layout({children}){
  const{user,logout}=useAuth();const[loginOpen,setLoginOpen]=useState(false);const[loginError,setLoginError]=useState('');const[installPrompt,setInstallPrompt]=useState(null)
  useEffect(()=>{const h=e=>{e.preventDefault();setInstallPrompt(e)};window.addEventListener('beforeinstallprompt',h);return()=>window.removeEventListener('beforeinstallprompt',h)},[])
  const install=async()=>{if(!installPrompt)return;await installPrompt.prompt();setInstallPrompt(null)}
  return <div className="app-shell"><header className="topbar"><Link className="brand" to="/"><img src="/prevora-mark.svg" alt="Prevora"/><span>Prevora</span></Link><div className="top-actions"><Link className="icon-btn" to="/pesquisa" aria-label="Pesquisar"><Search size={19}/></Link><button className="icon-btn" aria-label="Notificações"><Bell size={19}/></button><a className="icon-btn" href="https://petertecnet.com.br" aria-label="Ecossistema Peter Tecnet"><Grid2X2 size={19}/></a>{installPrompt&&<button className="icon-btn mobile-install" onClick={install} aria-label="Instalar Prevora"><Download size={19}/></button>}{user?<><Link className="user-chip" to="/perfil">{user.first_name||user.user_name}</Link><button className="icon-btn" onClick={logout} aria-label="Sair"><LogOut size={18}/></button></>:<button className="secondary compact" onClick={()=>setLoginOpen(true)}>Entrar</button>}<Link className="create-btn" to="/criar"><Plus size={18}/>Prever</Link></div></header><main className="page">{children}</main><nav className="bottom-nav">{nav.map(([to,Icon,label])=><NavLink key={to} to={to} end={to==='/' } className={({isActive})=>isActive?'active':''}><Icon size={20}/><span>{label}</span></NavLink>)}</nav>{loginOpen&&<div className="modal-backdrop" onMouseDown={()=>setLoginOpen(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setLoginOpen(false)}>×</button><img className="modal-logo" src="/prevora-mark.svg" alt=""/><h2>Entre na Prevora</h2><p>Explore sem login. Entre apenas quando quiser prever, estimar ou participar.</p>{loginError&&<p className="notice error">{loginError}</p>}<GoogleSignIn onSuccess={()=>setLoginOpen(false)} onError={e=>setLoginError(humanError(e,'Falha no login Google.'))}/></div></div>}</div>
}