import {Route,Routes} from 'react-router-dom'
import Layout from './components/Layout'
import HomePage from './pages/HomePage'
import CreatePage from './pages/CreatePage'
import ForecastPage from './pages/ForecastPage'
import FuturePage from './pages/FuturePage'
import RankingPage from './pages/RankingPage'
import ProfilePage from './pages/ProfilePage'
import SearchPage from './pages/SearchPage'
import LegalPage from './pages/LegalPage'
export default function App(){return <Layout><Routes><Route path="/" element={<HomePage/>}/><Route path="/criar" element={<CreatePage/>}/><Route path="/previsao/:slug" element={<ForecastPage/>}/><Route path="/futuro" element={<FuturePage/>}/><Route path="/ranking" element={<RankingPage/>}/><Route path="/perfil" element={<ProfilePage/>}/><Route path="/pesquisa" element={<SearchPage/>}/><Route path="/metodologia" element={<LegalPage type="metodologia"/>}/><Route path="/termos" element={<LegalPage type="termos"/>}/><Route path="/privacidade" element={<LegalPage type="privacidade"/>}/><Route path="/moderacao" element={<LegalPage type="moderacao"/>}/><Route path="*" element={<HomePage/>}/></Routes><footer className="footer"><span>Prevora · Peter Tecnet</span><nav><a href="/metodologia">Metodologia</a><a href="/termos">Termos</a><a href="/privacidade">Privacidade</a><a href="/moderacao">Moderação</a></nav></footer></Layout>}