export const predictions = [
  {
    id: 1,
    author: 'Prevora',
    category: 'Tecnologia',
    statement: 'Uma grande fabricante anunciará um novo dispositivo de IA pessoal até dezembro de 2027.',
    probability: 64,
    crowd: 58,
    deadline: '31 dez 2027',
    participants: 1284,
    status: 'Aberta',
  },
  {
    id: 2,
    author: 'Comunidade',
    category: 'Economia',
    statement: 'O Brasil terá pelo menos um trimestre com inflação anual abaixo de 4% antes de julho de 2027.',
    probability: 47,
    crowd: 51,
    deadline: '30 jun 2027',
    participants: 832,
    status: 'Aberta',
  },
  {
    id: 3,
    author: 'Prevora',
    category: 'Ciência',
    statement: 'Um novo recorde de eficiência de célula solar será publicado antes do fim de 2026.',
    probability: 72,
    crowd: 68,
    deadline: '31 dez 2026',
    participants: 611,
    status: 'Aberta',
  },
]
